repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ['--max-line-length=100', '--ignore=E309,E128,E501,W504,E402']